server:
   port: 8081

spring:
  application:
    name: catalog-service

logging:
  level:
    com.globalbooks.catalog: DEBUG
    org.springframework.ws: DEBUG

soap:
  service:
    url: http://localhost:8081/catalog/soap